// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StardewApp.Data;

#nullable disable

namespace StardewApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702191938_AttemptFKFixForUserCrop")]
    partial class AttemptFKFixForUserCrop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("StardewApp.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrowthTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IridiumPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SilverPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("StardewApp.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTiller")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TotalProfit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("StardewApp.Models.UserCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CropId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fertilizer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("SettingId");

                    b.ToTable("UserCrops");
                });

            modelBuilder.Entity("StardewApp.Models.UserCrop", b =>
                {
                    b.HasOne("StardewApp.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StardewApp.Models.Setting", null)
                        .WithMany("UserCrops")
                        .HasForeignKey("SettingId");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("StardewApp.Models.Setting", b =>
                {
                    b.Navigation("UserCrops");
                });
#pragma warning restore 612, 618
        }
    }
}
